apiVersion: apps/v1
kind: Deployment
metadata:
  name: muralidhar-device-mcp
  namespace: ai-user2
  labels:
    app: muralidhar-device-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muralidhar-device-mcp
  template:
    metadata:
      labels:
        app: muralidhar-device-mcp
    spec:
      containers:
      - name: device-mcp
        image: abhishek15c/device-mcp-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: sse-port
        env:
        - name: DEFAULT_TARGET_USER
          value: "root"
        - name: CROSS_GDB_PATH
          value: "gdb-multiarch"
        - name: SSH_KEY_PATH
          value: "/root/.ssh/id_rsa"
        - name: GDBSERVER_IPK_PATH
          value: "/tools/gdbserver.ipk"
        - name: DEFAULT_COLLAB_URL
          value: ""
        - name: DEFAULT_COLLAB_PAT
          value: ""
        volumeMounts:
        - name: ssh-key-volume
          mountPath: /root/.ssh
          readOnly: true
      volumes:
      - name: ssh-key-volume
        secret:
          secretName: device-agent-ssh-key
          defaultMode: 0400
          optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: muralidhar-device-mcp-service
  namespace: ai-user2
spec:
  type: NodePort
  selector:
    app: muralidhar-device-mcp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30724
