apiVersion: apps/v1
kind: Deployment
metadata:
  name: muralidhar-review-mcp
  namespace: ai-user2
  labels:
    app: muralidhar-review-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muralidhar-review-mcp
  template:
    metadata:
      labels:
        app: muralidhar-review-mcp
    spec:
      containers:
      - name: review-mcp
        image: abhishek15c/code-review-mcp-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: GERRIT_URL
          value: "https://wall.lge.com"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: muralidhar-review-mcp-service
  namespace: ai-user2
  labels:
    app: muralidhar-review-mcp
spec:
  type: NodePort
  selector:
    app: muralidhar-review-mcp
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31985
      protocol: TCP
